# Assuming your ASP.NET Core project is in a 'backend' folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Adjust this version based on your project

    - name: Restore .NET dependencies
      run: dotnet restore ./backend/your-project-file.csproj  # Path to your .csproj file

    - name: Build ASP.NET Core app
      run: dotnet build ./backend/your-project-file.csproj --configuration Release  # Specify path to .csproj

    - name: Run tests for ASP.NET Core app
      run: dotnet test ./backend/your-project-file.csproj --configuration Release  # Specify path to .csproj
